- src/main/java/sa/ejar/web/objects/ChangeTenantActivityPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/main/java/sa/ejar/web/pages/precondition/LoginPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
Test developed for TC_21 and TC_22
> Test developed for TC_21 and TC_22

- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
> Test developed for TC_23

- src/main/java/sa/ejar/web/objects/ChangeTenantActivityPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
> Test developed for TC_24

- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
Test developed for TC_25 and TC_26
> Test developed for TC_25 and TC_26

- src/main/java/sa/ejar/web/objects/ChangeTenantActivityPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
> Added C31, C32,C33 & C34

- src/main/java/sa/ejar/web/objects/ChangeTenantActivityPageObjects.java
- src/main/java/sa/ejar/web/objects/CommonMethodsPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
Test Developed for TC_27 TC_28 TC_29 TC_30
> Test Developed for TC_27 TC_28 TC_29 TC_30

- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
> Add new Test cases TC_01, TC_02_Change Tenant Activity

- src/main/java/sa/ejar/web/objects/ChangeTenantActivityPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
Add new test cases 
TC_03,
TC_04
> Add new test cases TC_03,TC_04

- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
Test developed for TC_51 TC_52 and TC_53
> Test developed for TC_51 TC_52 and TC_53

- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
Added 10 test cases and removed static keyword from page class
> Added 10 TC

- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
> added a step in TC_56

- src/test/java/sa/ejar/web/login/RevokeContract.java
> Revoke changes

- src/main/java/sa/ejar/web/objects/RentalIncidentsPageObjects.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/RentalIncidentsPage.java
- src/test/java/sa/ejar/web/login/RentalIncident.java
> Rental incident TC 76_85

- src/main/java/sa/ejar/web/objects/CommonMethodsPageObjects.java
- src/main/java/sa/ejar/web/objects/RentalIncidentsPageObjects.java
- src/main/java/sa/ejar/web/objects/RevokeContractPageObjects.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/RentalIncidentsPage.java
- src/test/java/sa/ejar/web/login/RentalIncident.java
- src/test/java/sa/ejar/web/login/RevokeContract.java
> Rental incident TC 96-96

- src/main/java/sa/ejar/web/NHCWebApplication.java
- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/objects/CommonMethodsPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep.java
> Change lessor 

- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/objects/CommonMethodsPageObjects.java
- src/main/java/sa/ejar/web/objects/SendContractForApprovalPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/RevokeContractPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep_Ejaz.java
Developed TC 6 to 22 Change lessor
> Developed TC 6 to 22 Change lessor

- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/objects/RevokeContractPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/RevokeContractPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep_Ejaz.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
> Change lessor TC 21-83

- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/precondition/LoginPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep_Ejaz.java
> Change lessor TC 163-223

- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep_Ibrahim.java
> Conflicts resolved 

- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/precondition/AddResidentialContractPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep_Ejaz.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep_Ibrahim.java
> Change lessor TC 391-425

- src/main/java/sa/ejar/web/objects/ManualRenewalPageObjects.java
- src/main/java/sa/ejar/web/pages/ManualRenewalPage.java
- src/main/java/sa/ejar/web/pages/precondition/AddResidentialContractPage.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
- src/test/java/sa/ejar/web/login/existing/ResidentialContract.java
> Updated changes

- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/precondition/AddResidentialContractPage.java
- src/test/java/sa/ejar/web/login/RentalIncident.java
- src/test/java/sa/ejar/web/login/TerminateContract.java
- src/test/java/sa/ejar/web/login/existing/ResidentialContract.java
Add Residential contract updated
> Add Residential contract updated

- src/main/java/sa/ejar/web/objects/precondition/AddResidentialContractPageObjects.java
- src/main/java/sa/ejar/web/pages/precondition/AddResidentialContractPage.java
- src/test/java/sa/ejar/web/login/existing/ResidentialContract.java
Add Residential contract new changes
> Add Residential contract new changes

- src/main/java/sa/ejar/web/NHCWebApplication.java
- src/main/java/sa/ejar/web/objects/pre_condition/AddPropertyPageObjects.java
- src/main/java/sa/ejar/web/objects/pre_condition/AddResidentialContractPageObjects.java
- src/main/java/sa/ejar/web/objects/pre_condition/LoginPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/ContractWaiverPage.java
- src/main/java/sa/ejar/web/pages/RentalIncidentsPage.java
- src/main/java/sa/ejar/web/pages/SendContractForApprovalPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddResidentialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/LoginPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
- src/test/java/sa/ejar/web/login/RentalIncident.java
- src/test/java/sa/ejar/web/login/pre_condition/ResidentialContract.java
> Commercial Contract

- src/main/java/sa/ejar/api/repo/APICollection.java
- src/main/java/sa/ejar/web/NHCWebApplication.java
- src/main/java/sa/ejar/web/objects/AutomaticRenewalPageObjects.java
- src/main/java/sa/ejar/web/objects/pre_condition/AddCommercialContractObjects.java
- src/main/java/sa/ejar/web/objects/pre_condition/AddResidentialContractPageObjects.java
- src/main/java/sa/ejar/web/pages/AutomaticRenewalPage.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddResidentialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddSubleaseContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/CreateNewCommercialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/LoginPage.java
- src/test/java/sa/ejar/web/login/AutomaticRenewal.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
- src/test/java/sa/ejar/web/login/ManualRenewal.java
- src/test/java/sa/ejar/web/login/RentalIncident.java
- src/test/java/sa/ejar/web/login/RevokeContract.java
- src/test/java/sa/ejar/web/login/pre_condition/AddCommercialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/ResidentialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/SubleaseContract.java
Commercial and Sublease contracts are added in pre-conditions
> Commercial and Sublease contracts are added in pre-conditions 

- src/main/java/sa/ejar/web/pages/ChangeTenantActivityPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/test/java/sa/ejar/web/login/ChangeTenantActivity.java
> update project 8

- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
> New updates

- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
> Date method updated

- src/main/java/sa/ejar/web/objects/pre_condition/AddResidentialContractPageObjects.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddResidentialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/CreateNewCommercialContractPage.java
- src/test/java/sa/ejar/web/login/pre_condition/AddCommercialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/AwqafCommercialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/AwqafResidentialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/ResidentialContract.java
> Updated Submit contract Flow

- src/main/java/sa/ejar/web/objects/pre_condition/AddResidentialContractPageObjects.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/main/java/sa/ejar/web/pages/ContractWaiverPage.java
- src/main/java/sa/ejar/web/pages/RevokeContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddResidentialContractPage.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
- src/test/java/sa/ejar/web/login/RevokeContract.java
- src/test/java/sa/ejar/web/login/pre_condition/AddCommercialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/ResidentialContract.java
> Updates to contract classes

- src/main/java/sa/ejar/web/objects/ContractWaiverPageObjects.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddResidentialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/CreateNewCommercialContractPage.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
- src/test/java/sa/ejar/web/login/pre_condition/AwqafSubleaseContract.java
Developed Awqaf Sublease contracts
> Developed Awqaf Sublease contracts

- src/main/java/sa/ejar/web/objects/pre_condition/AddResidentialContractPageObjects.java
- src/main/java/sa/ejar/web/pages/ContractWaiverPage.java
- src/main/java/sa/ejar/web/pages/MoveInMoveOutUnitsPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/AddResidentialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/CreateNewCommercialContractPage.java
- src/main/java/sa/ejar/web/pages/pre_condition/LoginPage.java
- src/test/java/sa/ejar/web/login/ContractWaiver.java
- src/test/java/sa/ejar/web/login/pre_condition/AddCommercialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/AwqafCommercialContract.java
- src/test/java/sa/ejar/web/login/pre_condition/AwqafSubleaseContract.java
Changes in commercial contracts
> Changes in commercial contracts

- src/main/java/sa/ejar/web/objects/ChangeLessor_LessorRepPageObjects.java
- src/main/java/sa/ejar/web/pages/ChangeLessor_LessorRepPage.java
- src/main/java/sa/ejar/web/pages/CommonMethodsPage.java
- src/test/java/sa/ejar/web/login/ChangeLessor_LessorRep.java
- src/test/java/sa/ejar/web/login/pre_condition/ResidentialContract.java
New changes during execution (Change lessor)
> New changes during execution (Change lessor)

- src/test/java/sa/ejar/web/login/ManualRenewal.java
> Updated file Manual Renewal

- src/main/java/sa/ejar/web/pages/ManualRenewalPage.java
- src/test/java/sa/ejar/web/login/ManualRenewal.java
New changes during execution (manual renewal) 3
> New changes during execution (manual renewal) 3

- src/main/java/sa/ejar/web/pages/ManualRenewalPage.java
- src/test/java/sa/ejar/web/login/ManualRenewal.java
> Updated file Manual Renewal 2

- src/main/java/sa/ejar/web/objects/ManualRenewalPageObjects.java
- src/main/java/sa/ejar/web/pages/ManualRenewalPage.java
- src/main/java/sa/ejar/web/pages/SendContractForApprovalPage.java
- src/test/java/sa/ejar/web/login/ManualRenewal.java
> Updated file Manual Renewal 3

- src/test/java/sa/ejar/web/login/ManualRenewal.java
New changes during execution (manual renewal) 4
> New changes during execution (manual renewal) 4
